// imports.gen.c — GERADO por new-port-arm.sh para 'nfstest' (libapp.so)
// 540 imports. Resolução: fallback dlsym + src/imports.c (shims).
#include "imports.h"
#include "so_util.h"
#include <stdio.h>

FILE *stderr_fake;
DynLibFunction dynlib_functions[] = {
    {"__nfstest_dummy__", 0}, /* sentinela; resolução real = dlsym+imports.c */
};
size_t dynlib_numfunctions = sizeof(dynlib_functions)/sizeof(dynlib_functions[0]);

// ============ referência: imports por categoria (do recon) ============
//   pass  abort
//   pass  accept
//   pass  access
//   UNKNOWN  acosf
//   abi  __aeabi_d2lz
//   abi  __aeabi_d2uiz
//   abi  __aeabi_d2ulz
//   abi  __aeabi_f2lz
//   abi  __aeabi_f2ulz
//   abi  __aeabi_l2f
//   abi  __aeabi_memclr
//   abi  __aeabi_memclr4
//   abi  __aeabi_memclr8
//   abi  __aeabi_memcpy
//   abi  __aeabi_memcpy4
//   abi  __aeabi_memcpy8
//   abi  __aeabi_memmove
//   abi  __aeabi_memmove4
//   abi  __aeabi_memset
//   abi  __aeabi_memset4
//   abi  __aeabi_memset8
//   abi  __aeabi_ul2f
//   UNKNOWN  AndroidBitmap_getInfo
//   UNKNOWN  AndroidBitmap_lockPixels
//   UNKNOWN  AndroidBitmap_unlockPixels
//   liblog  __android_log_assert
//   liblog  __android_log_print
//   liblog  __android_log_write
//   UNKNOWN  asinf
//   pass  atan2f
//   pass  atoi
//   UNKNOWN  basename
//   pass  bind
//   pass  calloc
//   pass  ceil
//   pass  ceilf
//   pass  chdir
//   UNKNOWN  chmod
//   UNKNOWN  clock
//   pass  clock_gettime
//   pass  close
//   pass  closedir
//   pass  connect
//   pass  cosf
//   UNKNOWN  _ctype_
//   cxx  __cxa_atexit
//   cxx  __cxa_bad_typeid
//   cxx  __cxa_finalize
//   cxx  __cxa_guard_acquire
//   cxx  __cxa_guard_release
//   cxx  __cxa_pure_virtual
//   UNKNOWN  dladdr
//   UNKNOWN  dlclose
//   UNKNOWN  dlerror
//   UNKNOWN  dlopen
//   UNKNOWN  dlsym
//   pass  dup2
//   UNKNOWN  __dynamic_cast
//   egl  eglGetProcAddress
//   pass  __errno
//   UNKNOWN  execl
//   UNKNOWN  execv
//   pass  exit
//   pass  expf
//   pass  fclose
//   pass  fcntl
//   pass  fdopen
//   UNKNOWN  feof
//   UNKNOWN  ferror
//   pass  fflush
//   pass  fgetc
//   pass  fgets
//   pass  fileno
//   pass  floor
//   pass  floorf
//   pass  fmod
//   UNKNOWN  FMOD_EventSystem_Create
//   pass  fmodf
//   UNKNOWN  FMOD_Memory_Initialize
//   pass  fopen
//   UNKNOWN  fork
//   pass  fprintf
//   pass  fputc
//   pass  fread
//   pass  free
//   UNKNOWN  freeaddrinfo
//   pass  fseek
//   pass  fstat
//   UNKNOWN  fsync
//   pass  ftell
//   UNKNOWN  ftruncate
//   UNKNOWN  fwide
//   pass  fwrite
//   UNKNOWN  gai_strerror
//   UNKNOWN  getaddrinfo
//   UNKNOWN  getauxval
//   pass  getc
//   pass  getcwd
//   UNKNOWN  getegid
//   pass  getenv
//   UNKNOWN  geteuid
//   UNKNOWN  getgid
//   pass  gethostbyname
//   UNKNOWN  gethostname
//   UNKNOWN  getnameinfo
//   UNKNOWN  getpeername
//   pass  getpid
//   UNKNOWN  getpwuid_r
//   pass  getsockname
//   pass  getsockopt
//   pass  gettimeofday
//   UNKNOWN  getuid
//   gles  glActiveTexture
//   gles  glAttachShader
//   gles  glBindAttribLocation
//   gles  glBindBuffer
//   gles  glBindFramebuffer
//   gles  glBindRenderbuffer
//   gles  glBindTexture
//   gles  glBlendColor
//   gles  glBlendEquation
//   gles  glBlendEquationSeparate
//   gles  glBlendFunc
//   gles  glBlendFuncSeparate
//   gles  glBufferData
//   gles  glBufferSubData
//   gles  glCheckFramebufferStatus
//   gles  glClear
//   gles  glClearColor
//   gles  glClearDepthf
//   gles  glClearStencil
//   gles  glColorMask
//   gles  glCompileShader
//   gles  glCompressedTexImage2D
//   gles  glCompressedTexSubImage2D
//   gles  glCopyTexImage2D
//   gles  glCopyTexSubImage2D
//   gles  glCreateProgram
//   gles  glCreateShader
//   gles  glCullFace
//   gles  glDeleteBuffers
//   gles  glDeleteFramebuffers
//   gles  glDeleteProgram
//   gles  glDeleteRenderbuffers
//   gles  glDeleteShader
//   gles  glDeleteTextures
//   gles  glDepthFunc
//   gles  glDepthMask
//   gles  glDepthRangef
//   gles  glDetachShader
//   gles  glDisable
//   gles  glDisableVertexAttribArray
//   gles  glDrawArrays
//   gles  glDrawElements
//   gles  glEnable
//   gles  glEnableVertexAttribArray
//   gles  glFinish
//   gles  glFlush
//   gles  glFramebufferRenderbuffer
//   gles  glFramebufferTexture2D
//   gles  glFrontFace
//   gles  glGenBuffers
//   gles  glGenerateMipmap
//   gles  glGenFramebuffers
//   gles  glGenRenderbuffers
//   gles  glGenTextures
//   gles  glGetActiveAttrib
//   gles  glGetActiveUniform
//   gles  glGetAttachedShaders
//   gles  glGetAttribLocation
//   gles  glGetBooleanv
//   gles  glGetBufferParameteriv
//   gles  glGetBufferPointervOES
//   gles  glGetError
//   gles  glGetFloatv
//   gles  glGetFramebufferAttachmentParameteriv
//   gles  glGetIntegerv
//   gles  glGetProgramInfoLog
//   gles  glGetProgramiv
//   gles  glGetRenderbufferParameteriv
//   gles  glGetShaderInfoLog
//   gles  glGetShaderiv
//   gles  glGetShaderPrecisionFormat
//   gles  glGetShaderSource
//   gles  glGetString
//   gles  glGetTexParameterfv
//   gles  glGetTexParameteriv
//   gles  glGetUniformfv
//   gles  glGetUniformiv
//   gles  glGetUniformLocation
//   gles  glGetVertexAttribfv
//   gles  glGetVertexAttribiv
//   gles  glGetVertexAttribPointerv
//   gles  glHint
//   gles  glIsBuffer
//   gles  glIsEnabled
//   gles  glIsFramebuffer
//   gles  glIsProgram
//   gles  glIsRenderbuffer
//   gles  glIsShader
//   gles  glIsTexture
//   gles  glLineWidth
//   gles  glLinkProgram
//   gles  glMapBufferOES
//   gles  glPixelStorei
//   gles  glPolygonOffset
//   gles  glReadPixels
//   gles  glReleaseShaderCompiler
//   gles  glRenderbufferStorage
//   gles  glSampleCoverage
//   gles  glScissor
//   gles  glShaderBinary
//   gles  glShaderSource
//   gles  glStencilFunc
//   gles  glStencilFuncSeparate
//   gles  glStencilMask
//   gles  glStencilMaskSeparate
//   gles  glStencilOp
//   gles  glStencilOpSeparate
//   gles  glTexImage2D
//   gles  glTexParameterf
//   gles  glTexParameterfv
//   gles  glTexParameteri
//   gles  glTexParameteriv
//   gles  glTexSubImage2D
//   gles  glUniform1f
//   gles  glUniform1fv
//   gles  glUniform1i
//   gles  glUniform1iv
//   gles  glUniform2f
//   gles  glUniform2fv
//   gles  glUniform2i
//   gles  glUniform2iv
//   gles  glUniform3f
//   gles  glUniform3fv
//   gles  glUniform3i
//   gles  glUniform3iv
//   gles  glUniform4f
//   gles  glUniform4fv
//   gles  glUniform4i
//   gles  glUniform4iv
//   gles  glUniformMatrix2fv
//   gles  glUniformMatrix3fv
//   gles  glUniformMatrix4fv
//   gles  glUnmapBufferOES
//   gles  glUseProgram
//   gles  glValidateProgram
//   gles  glVertexAttrib1f
//   gles  glVertexAttrib1fv
//   gles  glVertexAttrib2f
//   gles  glVertexAttrib2fv
//   gles  glVertexAttrib3f
//   gles  glVertexAttrib3fv
//   gles  glVertexAttrib4f
//   gles  glVertexAttrib4fv
//   gles  glVertexAttribPointer
//   gles  glViewport
//   pass  gmtime
//   UNKNOWN  gmtime_r
//   abi  __gnu_Unwind_Find_exidx
//   UNKNOWN  if_nametoindex
//   pass  inet_ntop
//   pass  inet_pton
//   pass  ioctl
//   pass  isalnum
//   pass  isalpha
//   UNKNOWN  isgraph
//   pass  islower
//   UNKNOWN  isprint
//   pass  isspace
//   pass  isupper
//   UNKNOWN  isxdigit
//   UNKNOWN  kill
//   pass  listen
//   pass  localtime
//   UNKNOWN  longjmp
//   pass  lrand48
//   pass  lseek
//   UNKNOWN  lseek64
//   pass  malloc
//   pass  memchr
//   pass  memcmp
//   pass  memcpy
//   pass  memmove
//   UNKNOWN  memrchr
//   pass  memset
//   pass  mkdir
//   UNKNOWN  mlock
//   pass  mmap
//   pass  modf
//   pass  mprotect
//   pass  munmap
//   pass  nanosleep
//   pass  open
//   pass  opendir
//   pass  perror
//   pass  poll
//   pass  pow
//   pass  powf
//   UNKNOWN  prctl
//   pass  printf
//   pthread  pthread_attr_destroy
//   pthread  pthread_attr_getstack
//   pthread  pthread_attr_init
//   pthread  pthread_attr_setschedparam
//   pthread  pthread_attr_setschedpolicy
//   pthread  pthread_attr_setstack
//   pthread  pthread_attr_setstacksize
//   pthread  pthread_cond_broadcast
//   pthread  pthread_cond_destroy
//   pthread  pthread_cond_init
//   pthread  pthread_cond_signal
//   pthread  pthread_cond_timedwait
//   pthread  pthread_cond_wait
//   pthread  pthread_create
//   pthread  pthread_detach
//   pthread  pthread_equal
//   pthread  pthread_exit
//   pthread  pthread_getattr_np
//   pthread  pthread_getschedparam
//   pthread  pthread_getspecific
//   pthread  pthread_join
//   pthread  pthread_key_create
//   pthread  pthread_key_delete
//   pthread  pthread_mutexattr_destroy
//   pthread  pthread_mutexattr_init
//   pthread  pthread_mutexattr_setpshared
//   pthread  pthread_mutexattr_settype
//   pthread  pthread_mutex_destroy
//   pthread  pthread_mutex_init
//   pthread  pthread_mutex_lock
//   pthread  pthread_mutex_trylock
//   pthread  pthread_mutex_unlock
//   pthread  pthread_once
//   pthread  pthread_rwlock_destroy
//   pthread  pthread_rwlock_init
//   pthread  pthread_rwlock_rdlock
//   pthread  pthread_rwlock_unlock
//   pthread  pthread_rwlock_wrlock
//   pthread  pthread_self
//   pthread  pthread_setschedparam
//   pthread  pthread_setspecific
//   pass  putc
//   UNKNOWN  putchar
//   pass  puts
//   pass  qsort
//   UNKNOWN  raise
//   pass  read
//   pass  readdir
//   UNKNOWN  readdir_r
//   UNKNOWN  readlink
//   pass  realloc
//   pass  recv
//   pass  recvfrom
//   pass  rename
//   pass  rmdir
//   pass  roundf
//   UNKNOWN  sbrk
//   pass  sched_yield
//   pthread  sem_destroy
//   pthread  sem_getvalue
//   pthread  sem_init
//   pthread  sem_post
//   pthread  sem_timedwait
//   pthread  sem_trywait
//   pthread  sem_wait
//   pass  send
//   pass  sendto
//   UNKNOWN  setbuf
//   pass  setenv
//   UNKNOWN  setjmp
//   pass  setsockopt
//   UNKNOWN  __sF
//   pass  shutdown
//   UNKNOWN  sigaction
//   UNKNOWN  siglongjmp
//   UNKNOWN  sigprocmask
//   UNKNOWN  sigsetjmp
//   pass  sinf
//   pass  snprintf
//   pass  socket
//   UNKNOWN  socketpair
//   pass  sprintf
//   pass  sqrtf
//   pass  srand48
//   pass  sscanf
//   abi  __stack_chk_fail
//   abi  __stack_chk_guard
//   pass  stat
//   UNKNOWN  statfs
//   pass  strcasecmp
//   pass  strcat
//   pass  strchr
//   pass  strcmp
//   pass  strcpy
//   UNKNOWN  strcspn
//   pass  strdup
//   pass  strerror
//   UNKNOWN  strerror_r
//   pass  strlen
//   pass  strncasecmp
//   pass  strncmp
//   pass  strncpy
//   UNKNOWN  strpbrk
//   pass  strrchr
//   UNKNOWN  strspn
//   pass  strstr
//   pass  strtod
//   UNKNOWN  strtoimax
//   UNKNOWN  strtok_r
//   pass  strtol
//   UNKNOWN  strtoll
//   pass  strtoul
//   UNKNOWN  strtoull
//   UNKNOWN  strtoumax
//   UNKNOWN  syscall
//   pass  sysconf
//   UNKNOWN  system
//   pass  tanf
//   pass  time
//   UNKNOWN  timezone
//   pass  tolower
//   UNKNOWN  _tolower_tab_
//   pass  toupper
//   UNKNOWN  tzname
//   UNKNOWN  tzset
//   UNKNOWN  ungetc
//   pass  unlink
//   UNKNOWN  unsetenv
//   UNKNOWN  utime
//   UNKNOWN  vfprintf
//   pass  vsnprintf
//   UNKNOWN  waitpid
//   pass  write
//   UNKNOWN  _ZN2EA6Nimble6getEnvEv
//   UNKNOWN  _ZN2EA6Nimble9findClassEPKc
//   UNKNOWN  _ZN4FMOD11EventSystem11getCategoryEPKcPPNS_13EventCategoryE
//   UNKNOWN  _ZN4FMOD11EventSystem14getMusicSystemEPPNS_11MusicSystemE
//   UNKNOWN  _ZN4FMOD11EventSystem15getReverbPresetEPKcP22FMOD_REVERB_PROPERTIESPi
//   UNKNOWN  _ZN4FMOD11EventSystem15getSystemObjectEPPNS_6SystemE
//   UNKNOWN  _ZN4FMOD11EventSystem19setReverbPropertiesEPK22FMOD_REVERB_PROPERTIES
//   UNKNOWN  _ZN4FMOD11EventSystem23set3DListenerAttributesEiPK11FMOD_VECTORS3_S3_S3_
//   UNKNOWN  _ZN4FMOD11EventSystem4initEijPvj
//   UNKNOWN  _ZN4FMOD11EventSystem4loadEPKcP19FMOD_EVENT_LOADINFOPPNS_12EventProjectE
//   UNKNOWN  _ZN4FMOD11EventSystem6updateEv
//   UNKNOWN  _ZN4FMOD11EventSystem7releaseEv
//   UNKNOWN  _ZN4FMOD11EventSystem8getEventEPKcjPPNS_5EventE
//   UNKNOWN  _ZN4FMOD11EventSystem8getGroupEPKcbPPNS_10EventGroupE
//   UNKNOWN  _ZN4FMOD12ChannelGroup15getSystemObjectEPPNS_6SystemE
//   UNKNOWN  _ZN4FMOD12ChannelGroup6addDSPEPNS_3DSPEPPNS_13DSPConnectionE
//   UNKNOWN  _ZN4FMOD14EventParameter6keyOffEv
//   UNKNOWN  _ZN4FMOD14EventParameter8getValueEPf
//   UNKNOWN  _ZN4FMOD14EventParameter8setValueEf
//   UNKNOWN  _ZN4FMOD3DSP12setParameterEif
//   UNKNOWN  _ZN4FMOD3DSP7releaseEv
//   UNKNOWN  _ZN4FMOD5Event11getCategoryEPPNS_13EventCategoryE
//   UNKNOWN  _ZN4FMOD5Event11setCallbackEPF11FMOD_RESULTP10FMOD_EVENT23FMOD_EVENT_CALLBACKTYPEPvS5_S5_ES5_
//   UNKNOWN  _ZN4FMOD5Event12getParameterEPKcPPNS_14EventParameterE
//   UNKNOWN  _ZN4FMOD5Event14get3DOcclusionEPfS1_
//   UNKNOWN  _ZN4FMOD5Event14set3DOcclusionEff
//   UNKNOWN  _ZN4FMOD5Event15get3DAttributesEP11FMOD_VECTORS2_S2_
//   UNKNOWN  _ZN4FMOD5Event15getChannelGroupEPPNS_12ChannelGroupE
//   UNKNOWN  _ZN4FMOD5Event15set3DAttributesEPK11FMOD_VECTORS3_S3_
//   UNKNOWN  _ZN4FMOD5Event18setPropertyByIndexEiPvb
//   UNKNOWN  _ZN4FMOD5Event4stopEb
//   UNKNOWN  _ZN4FMOD5Event5startEv
//   UNKNOWN  _ZN4FMOD5Event7getInfoEPiPPcP15FMOD_EVENT_INFO
//   UNKNOWN  _ZN4FMOD5Event7getMuteEPb
//   UNKNOWN  _ZN4FMOD5Event7releaseEbb
//   UNKNOWN  _ZN4FMOD5Event7setMuteEb
//   UNKNOWN  _ZN4FMOD5Event8getPitchEPf21FMOD_EVENT_PITCHUNITS
//   UNKNOWN  _ZN4FMOD5Event8getStateEPj
//   UNKNOWN  _ZN4FMOD5Event8setPitchEf21FMOD_EVENT_PITCHUNITS
//   UNKNOWN  _ZN4FMOD5Event9getPausedEPb
//   UNKNOWN  _ZN4FMOD5Event9getVolumeEPf
//   UNKNOWN  _ZN4FMOD5Event9setPausedEb
//   UNKNOWN  _ZN4FMOD5Event9setVolumeEf
//   UNKNOWN  _ZN4FMOD5Sound7releaseEv
//   UNKNOWN  _ZN4FMOD6System11createSoundEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE
//   UNKNOWN  _ZN4FMOD6System11getCPUUsageEPfS1_S1_S1_S1_
//   UNKNOWN  _ZN4FMOD6System13setFileSystemEPF11FMOD_RESULTPKciPjPPvS6_EPFS1_S5_S5_EPFS1_S5_S5_jS4_S5_EPFS1_S5_jS5_EPFS1_P18FMOD_ASYNCREADINFOS5_ESA_i
//   UNKNOWN  _ZN4FMOD6System14setSpeakerModeE16FMOD_SPEAKERMODE
//   UNKNOWN  _ZN4FMOD6System15createDSPByTypeE13FMOD_DSP_TYPEPPNS_3DSPE
//   UNKNOWN  _ZN4FMOD6System16setDSPBufferSizeEji
//   UNKNOWN  _ZN4FMOD6System17getSoftwareFormatEPiP17FMOD_SOUND_FORMATS1_S1_P18FMOD_DSP_RESAMPLERS1_
//   UNKNOWN  _ZN4FMOD6System17setSoftwareFormatEi17FMOD_SOUND_FORMATii18FMOD_DSP_RESAMPLER
//   UNKNOWN  _ZN4FMOD6System20set3DSpeakerPositionE12FMOD_SPEAKERffb
//   UNKNOWN  _ZN4FMOD6System9playSoundE17FMOD_CHANNELINDEXPNS_5SoundEbPPNS_7ChannelE
//   UNKNOWN  _ZN4FMOD6System9setOutputE15FMOD_OUTPUTTYPE
//   UNKNOWN  _ZN4FMOD7Channel11setCallbackEPF11FMOD_RESULTP12FMOD_CHANNEL25FMOD_CHANNEL_CALLBACKTYPEPvS5_E
//   UNKNOWN  _ZN4FMOD7Channel11setPriorityEi
//   UNKNOWN  _ZN4FMOD7Channel4stopEv
//   UNKNOWN  _ZN4FMOD7Channel7setMuteEb
//   UNKNOWN  _ZN4FMOD7Channel9getPausedEPb
//   UNKNOWN  _ZN4FMOD7Channel9isPlayingEPb
//   UNKNOWN  _ZN4FMOD7Channel9setPausedEb
//   UNKNOWN  _ZN4FMOD7Channel9setVolumeEf
//   UNKNOWN  _ZNKSt11logic_error4whatEv
//   UNKNOWN  _ZNKSt13runtime_error4whatEv
//   UNKNOWN  _ZNKSt6__ndk119__shared_weak_count13__get_deleterERKSt9type_info
//   UNKNOWN  _ZNKSt6__ndk16locale9use_facetERNS0_2idE
//   UNKNOWN  _ZNKSt6__ndk18ios_base6getlocEv
//   UNKNOWN  _ZNSt11logic_errorC2EPKc
//   UNKNOWN  _ZNSt13runtime_errorC2EPKc
//   UNKNOWN  _ZNSt13runtime_errorD2Ev
//   UNKNOWN  _ZNSt6__ndk119__shared_weak_count12__add_sharedEv
//   UNKNOWN  _ZNSt6__ndk119__shared_weak_count14__release_weakEv
//   UNKNOWN  _ZNSt6__ndk119__shared_weak_count16__release_sharedEv
//   UNKNOWN  _ZNSt6__ndk119__shared_weak_countD2Ev
//   UNKNOWN  _ZNSt6__ndk14cerrE
//   UNKNOWN  _ZNSt6__ndk15ctypeIcE2idE
//   UNKNOWN  _ZNSt6__ndk15mutex4lockEv
//   UNKNOWN  _ZNSt6__ndk15mutex6unlockEv
//   UNKNOWN  _ZNSt6__ndk15mutexD1Ev
//   UNKNOWN  _ZNSt6__ndk16localeC1Ev
//   UNKNOWN  _ZNSt6__ndk16localeD1Ev
//   UNKNOWN  _ZNSt6__ndk17num_getIcNS_19istreambuf_iteratorIcNS_11char_traitsIcEEEEE2idE
//   UNKNOWN  _ZNSt6__ndk17num_putIcNS_19ostreambuf_iteratorIcNS_11char_traitsIcEEEEE2idE
//   UNKNOWN  _ZNSt6__ndk18ios_base4initEPv
//   UNKNOWN  _ZNSt6__ndk18ios_base5clearEj
//   UNKNOWN  _ZNSt6__ndk18ios_baseD2Ev
//   UNKNOWN  _ZNSt9bad_allocC1Ev
//   UNKNOWN  _ZNSt9bad_allocD1Ev
//   UNKNOWN  _ZNSt9exceptionD2Ev
//   UNKNOWN  _ZSt18uncaught_exceptionv
//   UNKNOWN  _ZTIa
//   UNKNOWN  _ZTIf
//   UNKNOWN  _ZTIi
//   UNKNOWN  _ZTINSt6__ndk119__shared_weak_countE
//   UNKNOWN  _ZTINSt6__ndk18ios_baseE
//   UNKNOWN  _ZTIs
//   UNKNOWN  _ZTISt13runtime_error
//   UNKNOWN  _ZTISt9exception
//   UNKNOWN  _ZTIt
//   UNKNOWN  _ZTVN10__cxxabiv117__class_type_infoE
//   UNKNOWN  _ZTVN10__cxxabiv119__pointer_type_infoE
//   UNKNOWN  _ZTVN10__cxxabiv120__function_type_infoE
//   UNKNOWN  _ZTVN10__cxxabiv120__si_class_type_infoE
//   UNKNOWN  _ZTVN10__cxxabiv121__vmi_class_type_infoE
//   UNKNOWN  _ZTVSt12length_error
